[[rec_provenance_prov-content_data-entity]]
[recommendation]
====
[%metadata]
identifier:: /rec/provenance/prov-content-data-entity

[.component,class=part]
--
For each data link:https://www.w3.org/TR/prov-o/#Entity[`prov:Entity`] definition
(<<req_provenance_prov-content_input-entity,PROV Job Inputs>>, <<req_provenance_prov-content_result-entity,PROV Job Results>>)
resulting from the job execution, the associated data SHOULD provide
a `xsi:type` of identifiable typing reference (e.g., `xsd:double`, `xsd:int`, `xsd:string`, etc.)
that corresponds to the supported type from the original process description, and if multiple are allowed (i.e., `oneOf`),
that corresponds to the specific one that was resolved.
--

[.component,class=part]
--
If a data entity corresponds to a file reference (i.e., URI provided by `href`), it SHOULD consider annotating
it with `wf4ever:File` or another equivalent representation.
--

[.component,class=part]
--
If a data entity corresponds to a directory hierarchy or a collection with multiple nested components
(e.g., URI provided by `collection` or a browsable object store), it SHOULD consider annotating
it with `prov:collection` and assign it a `prov:id`, where further contained data entities are linked
to the collection through `prov:hadMember` relations and `prov:ref` identifiers.
--

[.component,class=part]
--
If the size of a data entity is considered small (e.g., a literal value),
the entity SHOULD include a `prov:value` property with the corresponding value used or generated by the job execution.
--

[.component,class=part]
--
If the size of a data entity is considered large (e.g., a file or collection),
the entity SHOULD include a `prov:location` property with the absolute URI to where the data was provided from
in case of inputs and where the results are stored for outputs.
--

====
